Create FlexConfirmMailDefault.adml
FlexConfirmMail/Outlook pull request #22
Opened 2024-04-24 19:15 UTC by jorgeaaq70

Spanish Translation for policy

2024-04-25 06:29 UTC, HashidaTKS requested changes

2024-04-25 06:29 UTC, HashidaTKS commented on policy/es-ES/FlexConfirmMailDefault.adml
> +    </stringTable>
```suggestion
      <string id="SafeNewDomainsEnabled">Confirmar cuando algun destinatario con un dominio diferente a los existentes es agregado</string>
    </stringTable>
```

The item `SafeNewDomainsEnabled` is added on the current master branch, so we also need to translate it.
I have copied the message from https://github.com/FlexConfirmMail/Outlook/blob/master/Properties/Resources.es.resx#L340, but I'm not familiar with Spanish, so please confirm the message is right or not.

2024-04-25 16:33 UTC, jorgeaaq70 reviewed
the translation is correct

2024-04-26 14:25 UTC, HashidaTKS commented
Thank you for your contribution! @jorgeaaq70

2024-04-26 14:25 UTC, merged